config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'schools#index'
  resources :locations, only: [:index,:show]
  resources :languages, only: [:index,:show]
  resources :schools do
    resources :reviews
  end
  post   '/like/:review_id' => 'likes#like',   as: 'like'
  delete '/like/:review_id' => 'likes#unlike', as: 'unlike'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord

  enum  name: {
    "Ruby":1, "PHP":2,"Python":3,"Java":4,"HTML / CSS":5,
  }


  has_many :school_languages
  has_many :schools,through: :school_languages
end
22

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :review, counter_cache: :likes_count
  belongs_to :user
end

app/models/location.rb
class Location < ApplicationRecord

  enum  name:{
'北海道':1,'青森県':2,'岩手県':3,
'宮城県':4,'秋田県':5,'山形県':6,
'福島県':7,'茨城県':8,'栃木県':9,
'群馬県':10,'埼玉県':11,'千葉県':12,
'東京都':13,'横浜':14,'新潟県':15,
'富山県':16,'石川県':17,'福井県':18,
'山梨県':19,'長野県':20,'岐阜県':21,
'静岡県':22,'名古屋':23,'三重県':24,
'滋賀県':25,'京都府':26,'大阪':27,
'兵庫県':28,'奈良県':29,'和歌山県':30,
'鳥取県':31,'島根県':32,'岡山県':33,
'広島県':34,'山口県':35,'徳島県':36,
'香川県':37,'愛媛県':38,'高知県':39,
'福岡':40,'佐賀県':41,'長崎県':42,
'熊本県':43,'大分県':44,'宮崎県':45,
'鹿児島県':46,'沖縄県':47,'オンライン':48,
  }

  has_many  :school_locations
  has_many  :schools, through: :school_locations
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :school
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  validates :rate, :content_good, :content_bad, presence: true
  validates :rate,:numericality => {
    :less_than => 5,
  }
end

app/models/school.rb
class School < ApplicationRecord
  has_many :school_languages
  has_many :languages, through: :school_languages
  has_many :school_locations
  has_many :locations, through: :school_locations
  has_many :reviews

  def review_average
    if reviews.present?
      reviews.average(:rate).round(2)
    else
      puts "まだreviewが投稿されていません"
    end
  end
end

app/models/school_language.rb
class SchoolLanguage < ApplicationRecord
  belongs_to :language
  belongs_to :school
end

app/models/school_location.rb
class SchoolLocation < ApplicationRecord
  belongs_to :school
  belongs_to :location
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # mount_uploader :image_url, ImageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_many :reviews
  has_many :likes, dependent: :destroy
  has_many :like_reviews, through: :likes, source: :review

  validates :nickname, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :avatar])
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  before_action :set_language_school

  def index
  end

  def show
  end

  private
  def set_language_school
    @schools = School.order("created_at ASC")
    @language = Language.find(params[:id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :set_variables

  def like
    like = current_user.likes.new(review_id: @review.id)
    if like.save
      respond_to do |format|
        format.html
        format.json
      end
    else
      flash.now[:alert] = 'エラーが発生しました。'
    end
  end

  def unlike
    like = current_user.likes.find_by(review_id: @review.id)
    like.destroy
  end

  private

  def set_variables
    @review = Review.find(params[:review_id])
    @id_name = "#like-link-#{@review.id}"
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  before_action :set_location_school

  def index
  end

  def show
  end

  def set_location_school
    @schools = School.order("created_at ASC")
    @location = Location.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_school, except: [:index]

  def index
    @reviews = Review.order("id ASC")

  end

  def new
    @review = Review.new

  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to school_path(@school), notice: 'レビューが送信されました'
    else
      flash.now[:alert] = '入力内容に不備があります。'
      render :new
    end
  end

  def edit
  end

  def update
    if (@review.user_id == current_user.id or current_user.admin?) && @review.update(review_params)
      redirect_to school_path(@school), notice: "編集が完了しました"
    else
      flash.now[:alert] = '編集内容に不備があります'
      render :edit
    end
  end

  def destroy
    if (@review.user_id == current_user.id or current_user.admin?) && @review.destroy
      redirect_to school_path(@school), notice: "削除が完了しました"
    else
      flash.now[:alert] = '削除できませんでした'
      redirect_to school_path(@school)
    end
  end


  private

  def review_params
    params.require(:review).permit(:rate, :content_good, :content_bad, :school_id)
    .merge(school_id: params[:school_id],user_id: current_user.id)
  end

  def set_school
    @school = School.find(params[:school_id])
  end


  def set_review
    @review = Review.find(params[:id])
  end


end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  before_action :authenticate_user!, only: [:show]

  def index
    @schools = School.order("id ASC")
  end

  def show
    @school = School.find(params[:id])
    @reviews = @school.reviews.includes(:user)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  params.require(:user).permit(:nickname, :email,:avatar)

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/languages/show.html.haml
= render partial: 'schools/header', locals: { }
= render partial: 'schools/bread-crumbs', locals: { }
.main-contents
  .wrapper
    .items
      .items__genre
        .category__title
          .category__title__text
            = "#{@language.name}のスクール一覧"
        .item-index
          .items
            - @language.schools.each do |school|
              .item
                = link_to school_path(school), class: "item-link" do
                  = image_tag "#{school.image_url}", class:"item__image"

                  .item__name
                    %span.item__name__text
                      = school.name


= render partial: '/schools/footer', locals: { }

app/views/likes/_like.html.haml
.like-link{:id => "like-link-#{review.id}"}
  - if current_user.likes.find_by(review_id: review.id)
    = link_to unlike_path(review.id), method: :delete, remote: true do
      .iine__button
        ❤️いいね！ #{review.likes_count}
  - else
    = link_to like_path(review.id), method: :post, remote: true do
      .iine__button
        ♡️いいね！#{review.likes_count}

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", review: @review  )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", review: @review  )) %>');

app/views/locations/show.html.haml
= render partial: 'schools/header', locals: { }
= render partial: 'schools/bread-crumbs', locals: { }
.main-contents
  .wrapper
    .items
      .items__genre
        .category__title
          .category__title__text
            = "#{@location.name}のスクール一覧"
        .item-index
          .items
            - @location.schools.each do |school|
              .item
                = link_to school_path(school), class: "item-link" do
                  = image_tag "#{school.image_url}", class:"item__image"
                  .item__name
                    %span.item__name__text
                      = school.name
= render partial: '/schools/footer', locals: { }

app/views/schools/_bread-crumbs.html.haml
%nav.bread-container
  - case params.values_at :controller, :action

    - when ['schools','index']
    - breadcrumb :top
    = breadcrumbs separator: " &nbsp;&nbsp;&#12297;&nbsp; "

    - when ['schools','show']
    - breadcrumb :school_show
    = breadcrumbs separator: " &nbsp;&nbsp;&#12297;&nbsp; "

    - when ['reviews','new']
    - breadcrumb :review_show
    = breadcrumbs separator: " &nbsp;&nbsp;&#12297;&nbsp; "

    - when ['reviews','edit']
    - breadcrumb :review_edit
    = breadcrumbs separator: " &nbsp;&nbsp;&#12297;&nbsp; "

    - when ['locations','show']
    - breadcrumb :location_show
    = breadcrumbs separator: " &nbsp;&nbsp;&#12297;&nbsp; "

    - when ['languages','show']
    - breadcrumb :language_show
    = breadcrumbs separator: " &nbsp;&nbsp;&#12297;&nbsp; "

app/views/schools/_footer.html.haml
%footer
  %nav.footer-nav

    .footer-nav__title
      %h2.footer-nav__title__text
        techlogについて
        %ul.nav-lists
          %li.nav-lists__list
            = link_to "https://about.mercari.com/", class: "nav-lists__list__link" do
              会社概要（運営会社）
          %li.nav-lists__list
            = link_to "/jp/jobs/", class: "nav-lists__list__link" do
              採用情報
          %li.nav-lists__list
            = link_to "https://about.mercari.com/press/news/", class: "nav-lists__list__link" do
              プレスリリース
          %li.nav-lists__list
            = link_to "https://jp-news.mercari.com/", class: "nav-lists__list__link" do
              公式ブログ
          %li.nav-lists__list
            = link_to "/jp/logo-guidelines/", class: "nav-lists__list__link" do
              techlog利用ガイドライン
          = link_to "https://twitter.com/mercari_jp", class: "nav-lists__icon" do
            %svg.nav-lists__icon--twitter{"aria-hidden": "true", height: "16", viewbox: "0 0 21 16", width: "21"}
              %path{:d => "M6.343 15.969c7.61 0 11.773-6.134 11.773-11.444 0-.172 0-.345-.008-.517a8.303 8.303 0 0 0 2.066-2.086 8.576 8.576 0 0 1-2.38.635A4.07 4.07 0 0 0 19.616.329a8.377 8.377 0 0 1-2.63.973 4.186 4.186 0 0 0-3.019-1.27c-2.283 0-4.14 1.803-4.14 4.023 0 .314.041.62.106.918A11.866 11.866 0 0 1 1.404.769a3.936 3.936 0 0 0-.557 2.023c0 1.396.735 2.628 1.84 3.35a4.278 4.278 0 0 1-1.872-.503v.055c0 1.945 1.428 3.577 3.317 3.945-.347.094-.71.141-1.09.141-.266 0-.524-.023-.774-.07.524 1.6 2.057 2.76 3.865 2.792a8.452 8.452 0 0 1-5.14 1.725 8.19 8.19 0 0 1-.985-.054 12.02 12.02 0 0 0 6.335 1.796", :fill => "currentColor", "fill-rule" => "evenodd"}
          = link_to "https://www.facebook.com/mercarijp", class: "nav-lists__icon" do
            %svg.nav-lists__icon--facebook{"aria-hidden": "true", height: "16", viewbox: "0 0 16 16", width: "16"}
              %path{:d => "M15.111 0H.89A.889.889 0 0 0 0 .889V15.11c0 .491.398.889.889.889h7.658V9.813H6.469V7.391h2.078V5.613c0-2.066 1.262-3.193 3.11-3.193.623-.002 1.244.03 1.863.096v2.15h-1.276c-1.002 0-1.197.478-1.197 1.178v1.543h2.397l-.31 2.422h-2.087V16h4.064c.491 0 .889-.398.889-.889V.89A.889.889 0 0 0 15.111 0z", :fill => "currentColor", "fill-rule" => "evenodd"}

    .footer-nav__title
      %h2.footer-nav__title__text
        プライバシーと利用規約
      .privacy-nav
        .privacy-nav__left
          %ul.nav-lists
            %li.nav-lists__list
              = link_to "/jp/privacy/", class: "nav-lists__list__link" do
                プライバシーポリシー
            %li.nav-lists__list
              = link_to "/jp/tos/", class: "nav-lists__list__link" do
                techlog利用規約
            %li.nav-lists__list
              = link_to "/jp/tos_smartphone_support/", class:"nav-lists__list__link" do
                あんしんスマホサポート制度に関する利用特約
            %li.nav-lists__list
              = link_to "/jp/compliance/", class:"nav-lists__list__link" do
                コンプライアンスポリシー
        .privacy-nav__right
          %ul.nav-lists
            %li.nav-lists__list
              = link_to "/jp/data_security/", class: "nav-lists__list__link" do
                個人データの安全管理に係る基本方針
            %li.nav-lists__list
              =link_to "/jp/tokutei/", class:"nav-lists__list__link" do
                特定商取引に関する表記
            %li.nav-lists__list
              = link_to "/jp/shikin_kessai/", class:"nav-lists__list__link" do
                資金決裁法に基づく表示
            %li.nav-lists__list
              = link_to "https://about.mercari.com/csr/safety/", class: "nav-lists__list__link" do
                法令遵守と犯罪抑止のために

    .footer-nav__title-country
      %h2.footer-nav__title-country__text
        国
        %ul.nav-lists
          %li.nav-lists__list
            = link_to "", class: "nav-lists__list__link" do
              日本
            =link_to "", class:"nav-lists__list__link" do
              United&nbsp;States

app/views/schools/_header.html.haml
%header
  .wrapper
    .upper-contents
      .upper-contents__left
        = link_to "/", class: "upper-contents__left__icon" do
          = image_tag "toppage/emblemmatic-techlog-logo-268.png", class: "upper-contents__left__icon__src", alt: "Mercari"
    .lower-wrapper
      .lower-contents
        .lower-contents__left
          .drop-down
            = link_to "/", class: "lower-contents__left__search-1" do
              %svg.genre-icon{"aria-hidden": "true", height: "16", viewbox: "0 0 20 16", width: "20"}
                %path{d: "M18.799 15.25h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zm0-6h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zm0-6h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zM2 16a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0-6a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0-6a2 2 0 1 0 0-4 2 2 0 0 0 0 4z", fill: "currentColor", "fill-rule": "nonzero"}
              学べる言語から探す
            .lower-contents__left__search-1
          = link_to "/", class: "lower-contents__left__search-2" do
            %svg.genre-icon{"aria-hidden": "true", height: "16", viewbox: "0 0 23 16", width: "23"}
              %path{d: "M6.315 0L4.473 1.806 2.833.019.73 1.977l1.69 1.84L1.198 5.02c-1.594 1.594-1.594 4.188-.01 5.772L6.3 16h13.272a3.08 3.08 0 0 0 3.077-3.077V3.076A3.08 3.08 0 0 0 19.57 0H6.315zm13.46 12.925a.211.211 0 0 1-.205.205H7.504L3.227 8.771a1.226 1.226 0 0 1-.01-1.71L4.38 5.92l1.28 1.371a2.68 2.68 0 1 0 2.13-1.93L6.433 3.907 7.49 2.87h12.082a.211.211 0 0 1 .206.205v9.848h-.002z", fill: "currentColor", "fill-rule": "nonzero"}
            場所から探す
        .lower-contents__right
          - if user_signed_in?
            .lower-contents__right__logout
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'lower-contents__right__logout__button'
          - else
            .lower-contents__right__sign-up
              = link_to new_user_registration_path, class: "lower-contents__right__sign-up__button" do
                新規登録
            .lower-contents__right__log-in
              = link_to new_user_session_path, class: "lower-contents__right__log-in__button" do
                ログイン

app/views/schools/index.html.haml
= render partial: 'schools/header', locals: { }
.main-contents
  = image_tag "toppage/main_m.jpg", class: "back-image"
  .popularity-index
    %h2.index-genre
      場所から探す
    %div.genre
      %ul.genre__wrapper
        %li.genre__wrapper__list
          = link_to location_path(13), class: "genre__wrapper__list__name" do
            東京
            = image_tag "https://takeshi.top/wp-content/uploads/2017/06/prosch-sejuku.png", class:"genre__wrapper__list__image"
        %li.genre__wrapper__list
          = link_to location_path(14), class: "genre__wrapper__list__name" do
            横浜
        %li.genre__wrapper__list
          = link_to location_path(23), class: "genre__wrapper__list__name" do
            名古屋
        %li.genre__wrapper__list
          = link_to location_path(27), class: "genre__wrapper__list__name" do
            大阪
        %li.genre__wrapper__list
          = link_to location_path(40), class: "genre__wrapper__list__name" do
            福岡
        %li.genre__wrapper__list
          = link_to location_path(48), class: "genre__wrapper__list__name" do
            オンライン

  .popularity-index
    %h2.index-genre
      言語から探す
    %div.genre
      %ul.genre__wrapper
        %li.genre__wrapper__list
          = link_to language_path(1), class: "genre__wrapper__list__name" do
            Ruby
            = image_tag "https://takeshi.top/wp-content/uploads/2017/06/prosch-sejuku.png", class:"genre__wrapper__list__image"
        %li.genre__wrapper__list
          = link_to language_path(3), class: "genre__wrapper__list__name" do
            Python
        %li.genre__wrapper__list
          = link_to language_path(2), class: "genre__wrapper__list__name" do
            PHP
        %li.genre__wrapper__list
          = link_to language_path(4), class: "genre__wrapper__list__name" do
            Java
        %li.genre__wrapper__list
          = link_to language_path(5), class: "genre__wrapper__list__name" do
            HTML / CSS
  .wrapper
    .items
      .items__genre

        .items__genre__title
          %h3.items__genre__title__text
            スクール一覧

        .item-index
          .items
            - @schools.each do |school|
              .item
                = link_to school_path(school), class: "item-link" ,'data-turbolinks': false do
                  = image_tag "#{school.image_url}", class:"item__image"
                  .item__name
                    %span.item__name__text
                      = school.name
= render partial: 'schools/footer', locals: { }

app/views/schools/new.html.haml
.single-container
  = render partial: 'schools/header', locals: { }
  = render partial: 'schools/bread-crumbs', locals: { }

  %main.single-main
    %section.sell-main
      .sell-container
        .sell-container__inner
          %h2.sell-container__inner__title 追加するスクールの情報を入力
          = form_for @school, html: {class: "sell-form"} do |f|
            .sell-upload
              %h3.sell-upload__head
                スクール画像
                %span.form-require 必須
              %p.sell-upload__text
              .sell-upload__box
                .sell-upload-items
                  %ul
                = f.fields_for :images do |f_image|
                  = f_image.file_field :image_url, type: "file", multiple: true,  name: "item[images_attributes][][image]", class: "upload-drop-file sell-upload__box__items-have"
              %pre
                :preserve
                  クリックしてファイルをアップロード
            .sell-content
              .form-group
                %label.form-group__name
                  スクール名
                  %span.form-require 必須
                %div
                  = f.text_field :name, class: "input-default", placeholder: "例)TECH::EXPERT（必須 40文字まで)", value: ""
              .form-group-next
                %label.form-group-next__name
                  スクールの説明
                  %span.form-require 必須
                = f.text_area :detail, class: "textarea-default", placeholder: "例)テックエキスパートは、6月から受講料が値上がりし、SNSなどで悪い意味で話題になっていました。ですが、むしろ受講生は増えていて、受講したくても受講できないくらい応募が殺到しています。口コミ調査の結果としては、バリバリ学習を進めている人が多く、高額なだけあってか、受講生は本気であるという印象を受けます。（必須 1,000文字以内）", rows: "5"
              .form-group-next
                %label.form-group-next__name
                  オススメのコース
                  %span.form-require 必須
                = f.text_field :detail, class: "textarea-default", placeholder: "例)転職コース（必須 40文字まで)", rows: "2"
              .form-group-next
                %label.form-group-next__name
                  こんな人にマッチ
                  %span.form-require 必須
                = f.text_field :detail, class: "textarea-default", placeholder: "例)プログラミングの基礎を身につけてから転職したい人（必須 40文字まで)", rows: "5"
            .sell-content
              .sell-form-wrapper
                %h3.sell-sub-head スクールの詳細
                .sell-form-box
                  #form-group-first.form-group-first
                    %label.form-group-first__name
                      スクール所在地
                      %span.form-require 必須
                    #select-wrap
                    .field
                      - %w(東京 大阪 名古屋 福岡 オンライン).each.with_index do |location,i|
                        %label
                          = check_box_tag 'samurai[ingredients][]', ingredient,false,id:"samurai_ingredients_#{i}"
                          = ingredient
                      -# = f.select :location_id, prompt: "---"
                      -# = f.select :category_id, @category_parents, prompt: "---"
                  .form-group-second
                    %label.form-group-second__name
                      学べる言語
                      %span.form-require 必須
                    .select-wrap

            .sell-content.sell-btn-box
              %div
                -# %p.text
                -#   = link_to "https://www.mercari.com/jp/help_center/getting_started/prohibited_items/", target: "_blank" do
                -#     禁止されている出品
                -#   、
                -#   = link_to "https://www.mercari.com/jp/help_center/getting_started/prohibited_conduct/", target: "_blank" do
                -#     行為
                -#   を必ずご確認ください。
                -# %p.text
                -#   またブランド品でシリアルナンバー等がある場合はご記載ください。
                -#   = link_to "https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/", target: "_blank" do
                -#     偽ブランドの販売
                -#   は犯罪であり処罰される可能性があります。
                -# %p.text
                -#   また、出品をもちまして
                -#   = link_to "https://www.mercari.com/jp/seller_terms/", target: "_blank" do
                -#     加盟店規約
                -#   に同意したことになります。
              = f.submit "スクールを追加する", class:"red-button"
              = link_to "", class: "gray-button" do
                もどる

-# = render partial: 'schools/footer', locals: { }

app/views/schools/show.html.haml
= render partial: 'schools/header', locals: { }
= render partial: 'schools/bread-crumbs', locals: { }

.item-detail-wrapper
  .item-box-container
    %h1.item-name
      = @school.name

    .item-main-content
      .item__photos
        = link_to "#{@school.company_url}", class: "item-link" ,'data-turbolinks': false do
          = image_tag "#{@school.image_url}", class:"item__main-photo"
      %table.item-detail-table
        %tbody
          %tr
            %th 口コミ評価平均
            %td
              -if @reviews.present?
                = @school.review_average
              -else
                まだレビューが投稿されていません


          %tr
            %th 場所
            %td
              %ul
                %li
                  - @school.locations.each do |school_location|
                    =link_to school_location.name,location_path(school_location)
          %tr
            %th 学べる言語
            %td
              %ul
                %li
                  - @school.languages.each do |shool_language|
                    =link_to shool_language.name,language_path(shool_language)
    .item-introduction
      %p
        = @school.detail
  .item__chat-message
    .message-container
      .message-content
        %ul.message-items
          - @school.reviews. each do |review|
            %li
              .list-left
                .user-avater
                  = image_tag review.user.avatar, class: 'user-avater' if review.user.avatar.attached?
              .list-right
                .user-name
                  = review.user.nickname
                .user-message-body
                  %ul.user-message-body__list
                    - if user_signed_in? && current_user.id == review.user_id or current_user.admin?
                      %li
                        = link_to '編集', edit_school_review_path(review,school_id: review.school_id)
                      %li
                        = link_to '削除', school_review_path(review,school_id: review.school_id), method: :delete
                  %h3 【評価点】
                  .user-message-body__text
                    = review.rate

                  %h3 【スクールの良かった点】
                  .user-message-body__text
                    = review.content_good

                  %h3 【スクールの悪かった点】
                  .user-message-body__text
                  = review.content_bad

                  .user-message-body__icons
                    .user-message-body__icons-left
                      = render partial: "reviews/reviews", locals: { review: review}
                      %span
                      #{review.updated_at.strftime("%Y/%m/%d %H:%M") }の投稿
                    .user-message-body__icons-right
                      = fa_icon "flag-o", class:"icon-flag"
                    .icon-balloon
        .message-content
          %form.message-form
            %p
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %button
              = link_to 'このスクールのレビューを投稿する', new_school_review_path(@school,@review), class:"comment-btn"
= render partial: '/schools/footer', locals: { }

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'